"""empty message

Revision ID: 22df80c026b9
Revises: dc4919cce3c9
Create Date: 2024-11-23 19:13:36.939829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22df80c026b9'
down_revision = 'dc4919cce3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
