"""empty message

Revision ID: 532aaa11a7af
Revises: 044c89a4c49d
Create Date: 2024-11-23 17:47:38.221442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532aaa11a7af'
down_revision = '044c89a4c49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Enum('LOW', 'HIGH', 'MEDIUM', name='messageimportance'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
