"""empty message

Revision ID: 72be86f05e95
Revises: 18877edd03aa
Create Date: 2024-11-16 16:19:17.591778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72be86f05e95'
down_revision = '18877edd03aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
