"""empty message

Revision ID: 688d02b7d603
Revises: de45fa64dd83
Create Date: 2024-11-16 14:49:47.674456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688d02b7d603'
down_revision = 'de45fa64dd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
